import type { Permission } from "@/lib/auth/permissions";
import { FEEDBACK_PERMISSION } from "@/lib/feedback/access";
import { staffCopy } from "./copy";
import { STAFF_NAV, type StaffNavKey } from "./nav";

export type FinderKind = "setting" | "action" | "page";
type Words = { en: string; mr: string };
export type FinderEntry = {
  /** Stable id, used for option ids and tests. */
  id: string;
  kind: FinderKind;
  title: Words;
  /** Where it lives, shown under the title. */
  hint?: Words;
  href: string;
  /** Only people holding this see the entry. The page itself still checks. */
  permission: Permission;
  /** Other words people type for it. */
  keywords: string[];
  keywordsMr: string[];
};

const STORE: Words = { en: "Store settings", mr: "दुकानाची सेटिंग्ज" };
const under = (parent: Words, en: string, mr: string): Words => ({
  en: `${parent.en} › ${en}`,
  mr: `${parent.mr} › ${mr}`,
});
const RULES = under(STORE, "Delivery rules", "वितरणाचे नियम");
const TIMES = under(STORE, "Delivery times", "वितरणाच्या वेळा");
const AREAS = under(STORE, "Service areas", "सेवा क्षेत्रे");
const TAX = under(STORE, "Business and tax", "व्यवसाय व कर");
const CHECKS = under(STORE, "Checks and search", "तपासणी व शोध");

const settings: FinderEntry[] = [
  {
    id: "settings.cutoff",
    kind: "setting",
    title: { en: "Same-day delivery cut-off time", mr: "त्याच दिवशी वितरणाची शेवटची वेळ" },
    hint: RULES,
    href: "/super-admin#delivery-rules",
    permission: "settings:write",
    keywords: ["same day", "cutoff", "cut off", "last order time", "before", "today delivery"],
    keywordsMr: ["त्याच दिवशी", "वेळ", "आज"],
  },
  {
    id: "settings.free-delivery",
    kind: "setting",
    title: { en: "Free delivery from (₹)", mr: "मोफत वितरण किती रुपयांपासून" },
    hint: RULES,
    href: "/super-admin#delivery-rules",
    permission: "settings:write",
    keywords: ["free delivery", "free shipping", "minimum order", "threshold", "free"],
    keywordsMr: ["मोफत", "फुकट", "वितरण", "डिलिव्हरी"],
  },
  {
    id: "settings.closed-dates",
    kind: "setting",
    title: { en: "Closed dates", mr: "दुकान बंद असलेल्या तारखा" },
    hint: RULES,
    href: "/super-admin#delivery-rules",
    permission: "settings:write",
    keywords: ["holiday", "blackout", "closed", "shut", "diwali", "festival", "leave"],
    keywordsMr: ["सुट्टी", "बंद", "सण", "दिवाळी"],
  },
  {
    id: "settings.weekly-holiday",
    kind: "setting",
    title: { en: "Closed every week on", mr: "दर आठवड्याची सुट्टी" },
    hint: RULES,
    href: "/super-admin#delivery-rules",
    permission: "settings:write",
    keywords: ["weekly off", "sunday", "holiday", "closed day", "day off"],
    keywordsMr: ["रविवार", "सुट्टी", "आठवडा"],
  },
  {
    id: "settings.weekly-times",
    kind: "setting",
    title: { en: "Weekly delivery times", mr: "आठवड्याच्या वितरण वेळा" },
    hint: TIMES,
    href: "/super-admin#weekly",
    permission: "settings:write",
    keywords: ["slot", "timing", "schedule", "delivery time", "window", "pause"],
    keywordsMr: ["वेळ", "स्लॉट", "वितरण"],
  },
  {
    id: "settings.slots",
    kind: "setting",
    title: { en: "Upcoming delivery slots", mr: "पुढचे वितरण स्लॉट" },
    hint: under(STORE, "Upcoming slots", "पुढचे स्लॉट"),
    href: "/super-admin#slots",
    permission: "settings:write",
    keywords: ["slot", "capacity", "booked", "close slot", "reopen", "full", "size"],
    keywordsMr: ["स्लॉट", "क्षमता", "बुकिंग"],
  },
  {
    id: "settings.areas",
    kind: "setting",
    title: { en: "Service areas and PIN codes", mr: "सेवा क्षेत्रे व पिन कोड" },
    hint: AREAS,
    href: "/super-admin#areas",
    permission: "settings:write",
    keywords: ["pincode", "pin code", "zone", "location", "area", "village", "deliver to", "serviceability"],
    keywordsMr: ["पिन", "क्षेत्र", "गाव", "ठिकाण"],
  },
  {
    id: "settings.delivery-fee",
    kind: "setting",
    title: { en: "Delivery fee (₹)", mr: "वितरण शुल्क (₹)" },
    hint: AREAS,
    href: "/super-admin#areas",
    permission: "settings:write",
    keywords: ["delivery charge", "fee", "shipping charge", "charges"],
    keywordsMr: ["शुल्क", "चार्ज", "वितरण"],
  },
  {
    id: "settings.cod-limit",
    kind: "setting",
    title: { en: "Cash on delivery limit (₹)", mr: "कॅश ऑन डिलिव्हरीची मर्यादा (₹)" },
    hint: AREAS,
    href: "/super-admin#areas",
    permission: "settings:write",
    keywords: ["cod", "cash", "limit", "largest order", "cash on delivery"],
    keywordsMr: ["रोख", "कॅश", "मर्यादा"],
  },
  {
    id: "settings.gstin",
    kind: "setting",
    title: { en: "GSTIN, legal name and address", mr: "जीएसटीआयएन, कायदेशीर नाव व पत्ता" },
    hint: TAX,
    href: "/super-admin#tax",
    permission: "settings:write",
    keywords: ["gst", "gstin", "tax", "invoice", "legal name", "igst", "cgst", "sgst", "business", "state", "address"],
    keywordsMr: ["जीएसटी", "कर", "पत्ता", "व्यवसाय"],
  },
  {
    id: "settings.grievance-officer",
    kind: "setting",
    title: { en: "Grievance officer", mr: "तक्रार निवारण अधिकारी" },
    hint: TAX,
    href: "/super-admin#grievance",
    permission: "settings:write",
    keywords: ["grievance", "complaint officer", "consumer", "contact page", "privacy", "policy", "dpdp"],
    keywordsMr: ["तक्रार", "अधिकारी", "संपर्क"],
  },
  {
    id: "settings.quote-terms",
    kind: "setting",
    title: { en: "Quotation terms", mr: "कोटेशनच्या अटी" },
    hint: TAX,
    href: "/super-admin#tax",
    permission: "settings:write",
    keywords: ["terms", "conditions", "payment terms", "quotation", "quote"],
    keywordsMr: ["अटी", "कोटेशन"],
  },
  {
    id: "settings.stock-approval",
    kind: "setting",
    title: { en: "Stock changes that need approval", mr: "मंजुरी लागणारे स्टॉक बदल" },
    hint: CHECKS,
    href: "/super-admin#stock-approval",
    permission: "settings:write",
    keywords: ["approval limit", "threshold", "units", "large stock change", "second owner"],
    keywordsMr: ["मंजुरी", "स्टॉक", "मर्यादा"],
  },
  {
    id: "settings.synonyms",
    kind: "setting",
    title: { en: "Search words that mean the same", mr: "समान अर्थाचे शोध शब्द" },
    hint: CHECKS,
    href: "/super-admin#synonyms",
    permission: "settings:write",
    keywords: ["synonyms", "search words", "alias", "other words", "spelling"],
    keywordsMr: ["शब्द", "शोध"],
  },
  {
    id: "settings.services",
    kind: "setting",
    title: { en: "Connected services", mr: "जोडलेल्या सेवा" },
    hint: CHECKS,
    href: "/super-admin#services",
    permission: "settings:write",
    keywords: ["razorpay", "payment gateway", "online payment", "upi", "sms", "cloudinary", "photos", "integrations"],
    keywordsMr: ["पेमेंट", "ऑनलाइन", "एसएमएस"],
  },
  {
    id: "settings.welcome-offer",
    kind: "setting",
    title: { en: "Welcome offer in the top bar", mr: "वरच्या पट्टीतील स्वागत ऑफर" },
    hint: { en: "Offers", mr: "ऑफर" },
    href: "/super-admin/promotions",
    permission: "promotion:write",
    keywords: ["welcome", "banner", "top bar", "coupon", "first order"],
    keywordsMr: ["स्वागत", "कूपन", "ऑफर"],
  },
  {
    id: "settings.gst-rate",
    kind: "setting",
    title: { en: "GST rate and HSN code of a product", mr: "उत्पादनाचा जीएसटी दर व एचएसएन कोड" },
    hint: { en: "Catalog › a product’s page › Tax", mr: "उत्पादने › उत्पादनाचे पान › कर" },
    href: "/admin/products",
    permission: "catalog:write",
    keywords: ["gst", "hsn", "tax rate", "product tax"],
    keywordsMr: ["जीएसटी", "कर", "एचएसएन"],
  },
  {
    id: "settings.roles",
    kind: "setting",
    title: { en: "What each staff role can do", mr: "प्रत्येक भूमिकेला काय करता येते" },
    hint: { en: "Staff & roles", mr: "कर्मचारी व भूमिका" },
    href: "/super-admin/staff#team",
    permission: "staff:manage",
    keywords: ["permissions", "access", "role", "admin", "owner", "can sign in"],
    keywordsMr: ["भूमिका", "परवानगी"],
  },
  {
    id: "settings.my-account",
    kind: "setting",
    title: { en: "My profile and password", mr: "माझी माहिती व पासवर्ड" },
    hint: { en: "My account", mr: "माझे खाते" },
    href: "/account",
    permission: "profile:own",
    keywords: ["password", "profile", "phone", "email", "my name", "sign in"],
    keywordsMr: ["पासवर्ड", "खाते", "फोन"],
  },
];

const actions: FinderEntry[] = [
  {
    id: "action.add-product",
    kind: "action",
    title: { en: "Add a product", mr: "नवीन उत्पादन जोडा" },
    hint: { en: "Catalog", mr: "उत्पादने" },
    href: "/admin/products/new",
    permission: "catalog:write",
    keywords: ["new product", "create item", "new item", "list product"],
    keywordsMr: ["उत्पादन", "नवीन", "वस्तू"],
  },
  {
    id: "action.adjust-stock",
    kind: "action",
    title: { en: "Adjust stock", mr: "स्टॉक बदला" },
    hint: { en: "Catalog › Stock", mr: "उत्पादने › स्टॉक" },
    href: "/admin/inventory",
    permission: "inventory:adjust",
    keywords: ["stock", "inventory", "quantity", "count", "restock", "sold out"],
    keywordsMr: ["स्टॉक", "माल", "संख्या"],
  },
  {
    id: "action.add-pack",
    kind: "action",
    title: { en: "Add a pack size", mr: "नवीन पॅक जोडा" },
    hint: { en: "Catalog › Stock", mr: "उत्पादने › स्टॉक" },
    href: "/admin/inventory?new=pack#new-pack",
    permission: "inventory:adjust",
    keywords: ["pack", "variant", "size", "box of"],
    keywordsMr: ["पॅक", "आकार"],
  },
  {
    id: "setting.push",
    kind: "setting",
    title: { en: "New-order notifications on this phone or PC", mr: "या फोन किंवा संगणकावर नवीन ऑर्डरच्या सूचना" },
    hint: { en: "Notifications", mr: "सूचना" },
    href: "/account/notifications#push",
    permission: "order:manage",
    keywords: ["push", "notifications", "notify", "alert", "new order alert", "phone alert", "turn on notifications"],
    keywordsMr: ["सूचना", "नोटिफिकेशन", "नवीन ऑर्डर"],
  },
  {
    id: "action.stock-sheet",
    kind: "action",
    title: { en: "Update stock from a spreadsheet", mr: "स्प्रेडशीटमधून स्टॉक बदला" },
    hint: { en: "Catalog › Stock", mr: "उत्पादने › स्टॉक" },
    href: "/admin/inventory?sheet=1#stock-sheet",
    permission: "inventory:adjust",
    keywords: ["csv", "excel", "spreadsheet", "stock sheet", "import stock", "upload stock", "bulk stock"],
    keywordsMr: ["स्टॉक शीट", "एक्सेल", "स्टॉक"],
  },
  {
    id: "action.add-aisle",
    kind: "action",
    title: { en: "Add a category", mr: "नवीन विभाग जोडा" },
    hint: { en: "Catalog › Categories", mr: "उत्पादने › विभाग" },
    href: "/admin/categories",
    permission: "catalog:write",
    keywords: ["category", "aisle", "section", "department"],
    keywordsMr: ["विभाग", "प्रकार"],
  },
  {
    id: "action.create-offer",
    kind: "action",
    title: { en: "Create an offer or coupon", mr: "ऑफर किंवा कूपन बनवा" },
    hint: { en: "Offers", mr: "ऑफर" },
    href: "/super-admin/promotions?edit=new#offer",
    permission: "promotion:write",
    keywords: ["coupon", "discount", "promo code", "sale", "deal"],
    keywordsMr: ["सवलत", "कूपन", "ऑफर"],
  },
  {
    id: "action.add-staff",
    kind: "action",
    title: { en: "Add a staff member or delivery partner", mr: "कर्मचारी किंवा डिलिव्हरी पार्टनर जोडा" },
    hint: { en: "Staff & roles", mr: "कर्मचारी व भूमिका" },
    href: "/super-admin/staff#add",
    permission: "staff:manage",
    keywords: ["employee", "team", "rider", "delivery boy", "delivery partner", "admin", "worker"],
    keywordsMr: ["कर्मचारी", "डिलिव्हरी", "रायडर"],
  },
  {
    id: "action.change-access",
    kind: "action",
    title: { en: "Change someone’s role or password", mr: "भूमिका किंवा पासवर्ड बदला" },
    hint: { en: "Staff & roles", mr: "कर्मचारी व भूमिका" },
    href: "/super-admin/staff#team",
    permission: "staff:manage",
    keywords: ["role", "access", "password", "remove staff", "can sign in"],
    keywordsMr: ["भूमिका", "पासवर्ड"],
  },
  {
    id: "action.add-school",
    kind: "action",
    title: { en: "Add a school", mr: "नवीन शाळा जोडा" },
    hint: { en: "Schools", mr: "शाळा" },
    href: "/super-admin/schools?edit=new#school",
    permission: "settings:write",
    keywords: ["school", "institute", "college"],
    keywordsMr: ["शाळा"],
  },
  {
    id: "action.add-area",
    kind: "action",
    title: { en: "Add a delivery area", mr: "नवीन वितरण क्षेत्र जोडा" },
    hint: AREAS,
    href: "/super-admin?area=new#area",
    permission: "settings:write",
    keywords: ["area", "pincode", "pin code", "village", "zone"],
    keywordsMr: ["क्षेत्र", "पिन", "गाव"],
  },
  {
    id: "action.add-weekly",
    kind: "action",
    title: { en: "Add a weekly delivery time", mr: "आठवड्याची वितरण वेळ जोडा" },
    hint: TIMES,
    href: "/super-admin#add-weekly",
    permission: "settings:write",
    keywords: ["slot", "timing", "new time", "delivery time"],
    keywordsMr: ["वेळ", "स्लॉट"],
  },
  {
    id: "action.one-off",
    kind: "action",
    title: { en: "Add a one-off delivery time", mr: "एका दिवसासाठी वितरण वेळ जोडा" },
    hint: TIMES,
    href: "/super-admin#one-off",
    permission: "settings:write",
    keywords: ["single date", "special", "extra slot", "festival", "one day"],
    keywordsMr: ["एक दिवस", "खास", "वेळ"],
  },
  {
    id: "action.reconcile-cash",
    kind: "action",
    title: { en: "Reconcile cash from deliveries", mr: "डिलिव्हरीची रोख रक्कम जुळवा" },
    hint: { en: "Cash on delivery", mr: "कॅश ऑन डिलिव्हरी" },
    href: "/admin/cod",
    permission: "cod:reconcile",
    keywords: ["cash", "cod", "collection", "handover", "settle", "rider cash"],
    keywordsMr: ["रोख", "कॅश", "हिशोब"],
  },
  {
    id: "action.review-approvals",
    kind: "action",
    title: { en: "Review changes waiting for approval", mr: "मंजुरीसाठी थांबलेले बदल पाहा" },
    hint: { en: "Approvals", mr: "मंजुरी" },
    href: "/super-admin/approvals",
    permission: "approval:review",
    keywords: ["approve", "price change", "pending", "new product", "reject"],
    keywordsMr: ["मंजुरी", "किंमत"],
  },
  {
    id: "action.start-refund",
    kind: "action",
    title: { en: "Start a refund", mr: "रिफंड सुरू करा" },
    hint: { en: "Refunds", mr: "रिफंड" },
    href: "/super-admin/refunds",
    permission: "refund:write",
    keywords: ["refund", "money back", "return money", "repay"],
    keywordsMr: ["रिफंड", "पैसे परत"],
  },
  {
    id: "action.find-order",
    kind: "action",
    title: { en: "Find an order", mr: "ऑर्डर शोधा" },
    hint: { en: "Overview › Orders", mr: "आढावा › ऑर्डर" },
    href: "/admin#orders",
    permission: "order:manage",
    keywords: ["order number", "track order", "bill"],
    keywordsMr: ["ऑर्डर"],
  },
  {
    id: "action.find-customer",
    kind: "action",
    title: { en: "Find a customer", mr: "ग्राहक शोधा" },
    hint: { en: "Customers", mr: "ग्राहक" },
    href: "/admin/customers",
    permission: "order:manage",
    keywords: ["customer", "buyer", "phone number", "who ordered"],
    keywordsMr: ["ग्राहक", "फोन"],
  },
];

/** Extra words for each menu page; titles come from the menu labels. */
const pageWords: Record<StaffNavKey, { keywords: string[]; keywordsMr: string[] }> = {
  overview: { keywords: ["home", "dashboard", "orders", "today", "work queue"], keywordsMr: ["आढावा", "ऑर्डर", "आज"] },
  chats: { keywords: ["chat", "help", "message", "reply", "inbox", "support"], keywordsMr: ["चॅट", "संदेश", "मदत"] },
  complaints: { keywords: ["complaint", "return", "damaged", "wrong item", "aftercare"], keywordsMr: ["तक्रार", "परत"] },
  catalog: { keywords: ["products", "catalog", "items", "price", "stock"], keywordsMr: ["उत्पादने", "किंमत", "स्टॉक"] },
  customers: { keywords: ["customer", "buyer", "phone"], keywordsMr: ["ग्राहक"] },
  feedback: {
    keywords: ["feedback", "rating", "stars", "comments", "reply", "delivery partner rating", "order rating"],
    keywordsMr: ["अभिप्राय", "रेटिंग", "तारे"],
  },
  reviews: { keywords: ["rating", "review", "stars", "reported"], keywordsMr: ["परीक्षण", "रेटिंग"] },
  cod: { keywords: ["cash", "cod", "reconcile", "collection", "rider"], keywordsMr: ["रोख", "कॅश"] },
  refunds: { keywords: ["refund", "money back"], keywordsMr: ["रिफंड"] },
  offers: { keywords: ["coupon", "discount", "promo", "offer", "sale"], keywordsMr: ["सवलत", "कूपन"] },
  analytics: { keywords: ["sales", "report", "numbers", "chart", "revenue", "best sellers"], keywordsMr: ["विक्री", "आकडे"] },
  schools: { keywords: ["school", "representative", "join link"], keywordsMr: ["शाळा"] },
  quotations: { keywords: ["quote", "quotation", "school order", "pricing"], keywordsMr: ["कोटेशन", "शाळा"] },
  marketplace: { keywords: ["school shop", "school marketplace", "shop for a school", "school basket", "school prices"], keywordsMr: ["शाळा", "दुकान"] },
  settings: { keywords: ["settings", "setup", "configuration", "delivery", "options"], keywordsMr: ["सेटिंग्ज"] },
  staff: { keywords: ["staff", "team", "employee", "roles", "access"], keywordsMr: ["कर्मचारी"] },
  approvals: { keywords: ["approve", "pending", "waiting", "price change"], keywordsMr: ["मंजुरी"] },
  audit: { keywords: ["log", "history", "who changed", "activity", "sign ins"], keywordsMr: ["नोंद", "इतिहास"] },
  deliveries: { keywords: ["my deliveries", "stops", "route", "deliver"], keywordsMr: ["डिलिव्हरी"] },
};

const menuPages: FinderEntry[] = STAFF_NAV.flatMap((group) =>
  group.items.map((item) => ({
    id: `page.${item.key}`,
    kind: "page" as const,
    title: { en: staffCopy.en.nav[item.key], mr: staffCopy.mr.nav[item.key] },
    hint: { en: staffCopy.en.groups[group.key], mr: staffCopy.mr.groups[group.key] },
    href: item.href,
    permission: item.permission,
    ...pageWords[item.key],
  })),
);

const ORDERS: Words = { en: "Overview › Orders", mr: "आढावा › ऑर्डर" };
const step = (id: string, en: string, mr: string, status: string, keywords: string[]): FinderEntry => ({
  id: `page.orders-${id}`,
  kind: "page",
  title: { en, mr },
  hint: ORDERS,
  href: `/admin?status=${status}#orders`,
  permission: status === "refund-owed" ? "refund:write" : "order:manage",
  keywords,
  keywordsMr: ["ऑर्डर"],
});

const otherPages: FinderEntry[] = [
  step("to-confirm", "Orders to confirm", "स्वीकारायच्या ऑर्डर", "to-confirm", ["new orders", "confirm", "accept", "placed"]),
  step("packing", "Orders being packed", "पॅक होत असलेल्या ऑर्डर", "packing", ["packing", "pick", "packed"]),
  step("ready", "Packed orders with no rider", "रायडर नसलेल्या पॅक ऑर्डर", "ready", ["assign rider", "ready", "no rider", "dispatch"]),
  step("on-the-way", "Orders on the way", "वाटेत असलेल्या ऑर्डर", "on-the-way", ["out for delivery", "on the way", "shipped"]),
  step("not-delivered", "Deliveries that didn’t go through", "न पोहोचलेल्या डिलिव्हरी", "not-delivered", ["failed", "attempted", "not delivered", "missed"]),
  step("delivered", "Delivered orders", "पोहोचलेल्या ऑर्डर", "delivered", ["delivered", "done", "completed"]),
  step("cancelled", "Cancelled orders", "रद्द ऑर्डर", "cancelled", ["cancelled", "canceled"]),
  step("refund-owed", "Orders owed a refund", "रिफंड देणे बाकी असलेल्या ऑर्डर", "refund-owed", ["refund owed", "shortfall", "missing items"]),
  {
    id: "page.feedback-attention",
    kind: "page",
    title: { en: "Low ratings to read", mr: "वाचायची कमी रेटिंग" },
    hint: { en: "Ratings & feedback", mr: "रेटिंग व अभिप्राय" },
    href: "/super-admin/feedback?tab=attention",
    permission: FEEDBACK_PERMISSION,
    keywords: ["low rating", "bad rating", "unhappy customer", "1 star", "2 stars", "needs attention"],
    keywordsMr: ["कमी रेटिंग", "नाराज ग्राहक"],
  },
  {
    id: "page.feedback-reviews",
    kind: "page",
    title: { en: "All product reviews", mr: "सर्व उत्पादन परीक्षणे" },
    hint: { en: "Ratings & feedback", mr: "रेटिंग व अभिप्राय" },
    href: "/super-admin/feedback?tab=reviews",
    permission: FEEDBACK_PERMISSION,
    keywords: ["product reviews", "hide review", "show review", "hidden reviews"],
    keywordsMr: ["परीक्षण", "लपवा"],
  },
  {
    id: "page.stock",
    kind: "page",
    title: { en: "Stock", mr: "स्टॉक" },
    hint: { en: "Catalog", mr: "उत्पादने" },
    href: "/admin/inventory",
    permission: "inventory:adjust",
    keywords: ["inventory", "low stock", "running low", "sold out"],
    keywordsMr: ["स्टॉक", "माल"],
  },
  {
    id: "page.aisles",
    kind: "page",
    title: { en: "Categories", mr: "विभाग" },
    hint: { en: "Catalog", mr: "उत्पादने" },
    href: "/admin/categories",
    permission: "catalog:write",
    keywords: ["categories", "category", "sections"],
    keywordsMr: ["विभाग"],
  },
  {
    id: "page.shop",
    kind: "page",
    title: { en: "View the shop", mr: "दुकान पाहा" },
    hint: { en: "What customers see", mr: "ग्राहकांना दिसणारे" },
    href: "/",
    permission: "profile:own",
    keywords: ["shop", "store front", "website", "home page", "customer view"],
    keywordsMr: ["दुकान", "वेबसाइट"],
  },
];

/** Everything the workspace search can find, before filtering by who's asking. */
export const FINDER_INDEX: FinderEntry[] = [...settings, ...actions, ...menuPages, ...otherPages];
