import type { Locale } from "../locale-types";
import type { FeedbackTag } from "./rules";

/** Everything a shopper reads while rating an order, in both languages. Pure data, so the popup can use it too. */
const en = {
  arrived: (number: string) => `Order ${number} arrived`,
  title: "How did we do?",
  starsLegend: "Rate this order",
  starNames: ["Very poor", "Poor", "Okay", "Good", "Excellent"],
  starLabel: (stars: number, name: string) => `${stars} ${stars === 1 ? "star" : "stars"} – ${name}`,
  pickStar: "Tap a star. One tap is enough.",
  pickStarFirst: "Tap a star first.",
  liked: "What did you like?",
  wrong: "What went wrong?",
  tags: {
    "on-time": "On time",
    "well-packed": "Well packed",
    "right-items": "Right items",
    "good-quality": "Good quality",
    "polite-partner": "Polite delivery partner",
    "easy-order": "Easy to order",
    late: "Late delivery",
    "item-missing": "Item missing",
    "wrong-item": "Wrong item",
    "damaged-item": "Damaged item",
    "poor-quality": "Poor quality",
    "rude-partner": "Rude delivery partner",
    "hard-order": "Hard to order",
  } satisfies Record<FeedbackTag, string>,
  rider: "Rate your delivery partner",
  more: "Tell us more",
  optional: "Optional",
  morePlaceholder: "A line or two about your order",
  notNow: "Not now",
  send: "Send",
  sending: "Sending…",
  done: "Done",
  close: "Close",
  thanksTitle: "Thank you!",
  thanks: "Your feedback reached the shop.",
  complaintLead: "Something wrong with an item? Report it and the shop will sort it out.",
  complaintLink: "Report a problem with an item",
  cardTitle: "How was this order?",
  cardLead: "Tap a star to tell the shop.",
  yourRating: "Your rating",
  ratedStars: (stars: number) => `${stars} of 5`,
  riderRated: "Delivery partner",
  shopReply: "Reply from the shop",
  errors: {
    signIn: "Please sign in again to continue.",
    notFound: "We couldn’t find that order.",
    notDelivered: "You can rate an order once it’s delivered.",
    tooLate: "This order is too old to rate now.",
    already: "You’ve already rated this order.",
    tooFast: "Too many tries. Please try again in a little while.",
    generic: "Couldn’t send your rating. Please try again.",
  },
  replyTitle: "The shop replied to your rating",
  replyBody: (number: string, reply: string) => `Order ${number}: ${reply}`,
};

const mr: typeof en = {
  arrived: (number) => `ऑर्डर ${number} पोहोचली`,
  title: "आमची सेवा कशी वाटली?",
  starsLegend: "या ऑर्डरला रेटिंग द्या",
  starNames: ["खूप वाईट", "वाईट", "ठीक", "चांगले", "उत्तम"],
  starLabel: (stars, name) => `${stars} ${stars === 1 ? "तारा" : "तारे"} – ${name}`,
  pickStar: "तारा निवडा. एक टॅप पुरेसा आहे.",
  pickStarFirst: "आधी तारा निवडा.",
  liked: "काय आवडले?",
  wrong: "काय चुकले?",
  tags: {
    "on-time": "वेळेवर",
    "well-packed": "नीट पॅक केलेले",
    "right-items": "बरोबर वस्तू",
    "good-quality": "चांगला दर्जा",
    "polite-partner": "नम्र डिलिव्हरी पार्टनर",
    "easy-order": "ऑर्डर करणे सोपे",
    late: "उशिरा वितरण",
    "item-missing": "वस्तू कमी आली",
    "wrong-item": "चुकीची वस्तू",
    "damaged-item": "खराब झालेली वस्तू",
    "poor-quality": "दर्जा चांगला नाही",
    "rude-partner": "डिलिव्हरी पार्टनर उद्धट",
    "hard-order": "ऑर्डर करणे अवघड",
  },
  rider: "डिलिव्हरी पार्टनरला रेटिंग द्या",
  more: "आणखी सांगा",
  optional: "ऐच्छिक",
  morePlaceholder: "तुमच्या ऑर्डरबद्दल एक-दोन ओळी",
  notNow: "आत्ता नको",
  send: "पाठवा",
  sending: "पाठवत आहोत…",
  done: "ठीक आहे",
  close: "बंद करा",
  thanksTitle: "धन्यवाद!",
  thanks: "तुमचा अभिप्राय दुकानापर्यंत पोहोचला.",
  complaintLead: "वस्तूमध्ये अडचण आहे? दुकानाला कळवा, म्हणजे ती सोडवता येईल.",
  complaintLink: "वस्तूची तक्रार नोंदवा",
  cardTitle: "ही ऑर्डर कशी वाटली?",
  cardLead: "तारा निवडून दुकानाला कळवा.",
  yourRating: "तुमचे रेटिंग",
  ratedStars: (stars) => `५ पैकी ${stars}`,
  riderRated: "डिलिव्हरी पार्टनर",
  shopReply: "दुकानाचे उत्तर",
  errors: {
    signIn: "पुढे जाण्यासाठी पुन्हा साइन इन करा.",
    notFound: "ही ऑर्डर सापडली नाही.",
    notDelivered: "ऑर्डर पोहोचल्यानंतर रेटिंग देता येईल.",
    tooLate: "या ऑर्डरला रेटिंग देण्याची मुदत संपली.",
    already: "तुम्ही या ऑर्डरला आधीच रेटिंग दिले आहे.",
    tooFast: "खूप वेळा प्रयत्न झाला. थोड्या वेळाने पुन्हा करा.",
    generic: "रेटिंग पाठवता आले नाही. पुन्हा प्रयत्न करा.",
  },
  replyTitle: "तुमच्या रेटिंगला दुकानाने उत्तर दिले",
  replyBody: (number, reply) => `ऑर्डर ${number}: ${reply}`,
};

export const feedbackCopy: Record<Locale, typeof en> = { en, mr };
export type FeedbackCopy = typeof en;
